/* Copyright (c) 2023  Hunter Whyte */
#ifndef _GPIO_H
#define _GPIO_H

void gpio_led_init(void);
void gpio_led_on(s32_t led_number);
void gpio_led_off(s32_t led_number);
void gpio_led_toggle(s32_t led_number);

#define GPIO0_BASE 0x44E07000
#define GPIO1_BASE 0x4804C000
#define GPIO2_BASE 0x481AC000
#define GPIO3_BASE 0x481AE000

/* USR GPIOs - connected active high to user LEDs - bbb schematic pg. 6 */
#define USR0 21 /* GPIO1_21 */
#define USR1 22 /* GPIO1_22 */
#define USR2 23 /* GPIO1_23 */
#define USR3 24 /* GPIO1_24 */

#define GPIO_REVISION_OFFSET 0x00000000
#define GPIO_SYSCONFIG_OFFSET 0x00000010
#define GPIO_EOI_OFFSET 0x00000020
#define GPIO_IRQSTATUS_RAW_0_OFFSET 0x00000024
#define GPIO_IRQSTATUS_RAW_1_OFFSET 0x00000028
#define GPIO_IRQSTATUS_0_OFFSET 0x0000002C
#define GPIO_IRQSTATUS_1_OFFSET 0x00000030
#define GPIO_IRQSTATUS_SET_0_OFFSET 0x00000034
#define GPIO_IRQSTATUS_SET_1_OFFSET 0x00000038
#define GPIO_IRQSTATUS_CLR_0_OFFSET 0x0000003C
#define GPIO_IRQSTATUS_CLR_1_OFFSET 0x00000040
#define GPIO_IRQWAKEN_0_OFFSET 0x00000044
#define GPIO_IRQWAKEN_1_OFFSET 0x00000048
#define GPIO_SYSSTATUS_OFFSET 0x00000114
#define GPIO_CTRL_OFFSET 0x00000130
#define GPIO_OE_OFFSET 0x00000134
#define GPIO_DATAIN_OFFSET 0x00000138
#define GPIO_DATAOUT_OFFSET 0x0000013C
#define GPIO_LEVELDETECT0_OFFSET 0x00000140
#define GPIO_LEVELDETECT1_OFFSET 0x00000144
#define GPIO_RISINGDETECT_OFFSET 0x00000148
#define GPIO_FALLINGDETECT_OFFSET 0x0000014C
#define GPIO_DEBOUNCENABLE_OFFSET 0x00000150
#define GPIO_DEBOUNCINGTIME_OFFSET 0x00000154
#define GPIO_CLEARDATAOUT_OFFSET 0x00000190
#define GPIO_SETDATAOUT_OFFSET 0x00000194

#define GPIO0_REVISION (GPIO0_BASE + GPIO_REVISION_OFFSET)
#define GPIO0_SYSCONFIG (GPIO0_BASE + GPIO_SYSCONFIG_OFFSET)
#define GPIO0_EOI (GPIO0_BASE + GPIO_EOI_OFFSET)
#define GPIO0_IRQSTATUS_RAW_0 (GPIO0_BASE + GPIO_IRQSTATUS_RAW_0_OFFSET)
#define GPIO0_IRQSTATUS_RAW_1 (GPIO0_BASE + GPIO_IRQSTATUS_RAW_1_OFFSET)
#define GPIO0_IRQSTATUS_0 (GPIO0_BASE + GPIO_IRQSTATUS_0_OFFSET)
#define GPIO0_IRQSTATUS_1 (GPIO0_BASE + GPIO_IRQSTATUS_1_OFFSET)
#define GPIO0_IRQSTATUS_SET_0 (GPIO0_BASE + GPIO_IRQSTATUS_SET_0_OFFSET)
#define GPIO0_IRQSTATUS_SET_1 (GPIO0_BASE + GPIO_IRQSTATUS_SET_1_OFFSET)
#define GPIO0_IRQSTATUS_CLR_0 (GPIO0_BASE + GPIO_IRQSTATUS_CLR_0_OFFSET)
#define GPIO0_IRQSTATUS_CLR_1 (GPIO0_BASE + GPIO_IRQSTATUS_CLR_1_OFFSET)
#define GPIO0_IRQWAKEN_0 (GPIO0_BASE + GPIO_IRQWAKEN_0_OFFSET)
#define GPIO0_IRQWAKEN_1 (GPIO0_BASE + GPIO_IRQWAKEN_1_OFFSET)
#define GPIO0_SYSSTATUS (GPIO0_BASE + GPIO_SYSSTATUS_OFFSET)
#define GPIO0_CTRL (GPIO0_BASE + GPIO_CTRL_OFFSET)
#define GPIO0_OE (GPIO0_BASE + GPIO_OE_OFFSET)
#define GPIO0_DATAIN (GPIO0_BASE + GPIO_DATAIN_OFFSET)
#define GPIO0_DATAOUT (GPIO0_BASE + GPIO_DATAOUT_OFFSET)
#define GPIO0_LEVELDETECT0 (GPIO0_BASE + GPIO_LEVELDETECT0_OFFSET)
#define GPIO0_LEVELDETECT1 (GPIO0_BASE + GPIO_LEVELDETECT1_OFFSET)
#define GPIO0_RISINGDETECT (GPIO0_BASE + GPIO_RISINGDETECT_OFFSET)
#define GPIO0_FALLINGDETECT (GPIO0_BASE + GPIO_FALLINGDETECT_OFFSET)
#define GPIO0_DEBOUNCENABLE (GPIO0_BASE + GPIO_DEBOUNCENABLE_OFFSET)
#define GPIO0_DEBOUNCINGTIME (GPIO0_BASE + GPIO_DEBOUNCINGTIME_OFFSET)
#define GPIO0_CLEARDATAOUT (GPIO0_BASE + GPIO_CLEARDATAOUT_OFFSET)
#define GPIO0_SETDATAOUT (GPIO0_BASE + GPIO_SETDATAOUT_OFFSET)

#define GPIO1_REVISION (GPIO1_BASE + GPIO_REVISION_OFFSET)
#define GPIO1_SYSCONFIG (GPIO1_BASE + GPIO_SYSCONFIG_OFFSET)
#define GPIO1_EOI (GPIO1_BASE + GPIO_EOI_OFFSET)
#define GPIO1_IRQSTATUS_RAW_0 (GPIO1_BASE + GPIO_IRQSTATUS_RAW_0_OFFSET)
#define GPIO1_IRQSTATUS_RAW_1 (GPIO1_BASE + GPIO_IRQSTATUS_RAW_1_OFFSET)
#define GPIO1_IRQSTATUS_0 (GPIO1_BASE + GPIO_IRQSTATUS_0_OFFSET)
#define GPIO1_IRQSTATUS_1 (GPIO1_BASE + GPIO_IRQSTATUS_1_OFFSET)
#define GPIO1_IRQSTATUS_SET_0 (GPIO1_BASE + GPIO_IRQSTATUS_SET_0_OFFSET)
#define GPIO1_IRQSTATUS_SET_1 (GPIO1_BASE + GPIO_IRQSTATUS_SET_1_OFFSET)
#define GPIO1_IRQSTATUS_CLR_0 (GPIO1_BASE + GPIO_IRQSTATUS_CLR_0_OFFSET)
#define GPIO1_IRQSTATUS_CLR_1 (GPIO1_BASE + GPIO_IRQSTATUS_CLR_1_OFFSET)
#define GPIO1_IRQWAKEN_0 (GPIO1_BASE + GPIO_IRQWAKEN_0_OFFSET)
#define GPIO1_IRQWAKEN_1 (GPIO1_BASE + GPIO_IRQWAKEN_1_OFFSET)
#define GPIO1_SYSSTATUS (GPIO1_BASE + GPIO_SYSSTATUS_OFFSET)
#define GPIO1_CTRL (GPIO1_BASE + GPIO_CTRL_OFFSET)
#define GPIO1_OE (GPIO1_BASE + GPIO_OE_OFFSET)
#define GPIO1_DATAIN (GPIO1_BASE + GPIO_DATAIN_OFFSET)
#define GPIO1_DATAOUT (GPIO1_BASE + GPIO_DATAOUT_OFFSET)
#define GPIO1_LEVELDETECT0 (GPIO1_BASE + GPIO_LEVELDETECT0_OFFSET)
#define GPIO1_LEVELDETECT1 (GPIO1_BASE + GPIO_LEVELDETECT1_OFFSET)
#define GPIO1_RISINGDETECT (GPIO1_BASE + GPIO_RISINGDETECT_OFFSET)
#define GPIO1_FALLINGDETECT (GPIO1_BASE + GPIO_FALLINGDETECT_OFFSET)
#define GPIO1_DEBOUNCENABLE (GPIO1_BASE + GPIO_DEBOUNCENABLE_OFFSET)
#define GPIO1_DEBOUNCINGTIME (GPIO1_BASE + GPIO_DEBOUNCINGTIME_OFFSET)
#define GPIO1_CLEARDATAOUT (GPIO1_BASE + GPIO_CLEARDATAOUT_OFFSET)
#define GPIO1_SETDATAOUT (GPIO1_BASE + GPIO_SETDATAOUT_OFFSET)

#define GPIO2_REVISION (GPIO2_BASE + GPIO_REVISION_OFFSET)
#define GPIO2_SYSCONFIG (GPIO2_BASE + GPIO_SYSCONFIG_OFFSET)
#define GPIO2_EOI (GPIO2_BASE + GPIO_EOI_OFFSET)
#define GPIO2_IRQSTATUS_RAW_0 (GPIO2_BASE + GPIO_IRQSTATUS_RAW_0_OFFSET)
#define GPIO2_IRQSTATUS_RAW_1 (GPIO2_BASE + GPIO_IRQSTATUS_RAW_1_OFFSET)
#define GPIO2_IRQSTATUS_0 (GPIO2_BASE + GPIO_IRQSTATUS_0_OFFSET)
#define GPIO2_IRQSTATUS_1 (GPIO2_BASE + GPIO_IRQSTATUS_1_OFFSET)
#define GPIO2_IRQSTATUS_SET_0 (GPIO2_BASE + GPIO_IRQSTATUS_SET_0_OFFSET)
#define GPIO2_IRQSTATUS_SET_1 (GPIO2_BASE + GPIO_IRQSTATUS_SET_1_OFFSET)
#define GPIO2_IRQSTATUS_CLR_0 (GPIO2_BASE + GPIO_IRQSTATUS_CLR_0_OFFSET)
#define GPIO2_IRQSTATUS_CLR_1 (GPIO2_BASE + GPIO_IRQSTATUS_CLR_1_OFFSET)
#define GPIO2_IRQWAKEN_0 (GPIO2_BASE + GPIO_IRQWAKEN_0_OFFSET)
#define GPIO2_IRQWAKEN_1 (GPIO2_BASE + GPIO_IRQWAKEN_1_OFFSET)
#define GPIO2_SYSSTATUS (GPIO2_BASE + GPIO_SYSSTATUS_OFFSET)
#define GPIO2_CTRL (GPIO2_BASE + GPIO_CTRL_OFFSET)
#define GPIO2_OE (GPIO2_BASE + GPIO_OE_OFFSET)
#define GPIO2_DATAIN (GPIO2_BASE + GPIO_DATAIN_OFFSET)
#define GPIO2_DATAOUT (GPIO2_BASE + GPIO_DATAOUT_OFFSET)
#define GPIO2_LEVELDETECT0 (GPIO2_BASE + GPIO_LEVELDETECT0_OFFSET)
#define GPIO2_LEVELDETECT1 (GPIO2_BASE + GPIO_LEVELDETECT1_OFFSET)
#define GPIO2_RISINGDETECT (GPIO2_BASE + GPIO_RISINGDETECT_OFFSET)
#define GPIO2_FALLINGDETECT (GPIO2_BASE + GPIO_FALLINGDETECT_OFFSET)
#define GPIO2_DEBOUNCENABLE (GPIO2_BASE + GPIO_DEBOUNCENABLE_OFFSET)
#define GPIO2_DEBOUNCINGTIME (GPIO2_BASE + GPIO_DEBOUNCINGTIME_OFFSET)
#define GPIO2_CLEARDATAOUT (GPIO2_BASE + GPIO_CLEARDATAOUT_OFFSET)
#define GPIO2_SETDATAOUT (GPIO2_BASE + GPIO_SETDATAOUT_OFFSET)

#define GPIO3_REVISION (GPIO3_BASE + GPIO_REVISION_OFFSET)
#define GPIO3_SYSCONFIG (GPIO3_BASE + GPIO_SYSCONFIG_OFFSET)
#define GPIO3_EOI (GPIO3_BASE + GPIO_EOI_OFFSET)
#define GPIO3_IRQSTATUS_RAW_0 (GPIO3_BASE + GPIO_IRQSTATUS_RAW_0_OFFSET)
#define GPIO3_IRQSTATUS_RAW_1 (GPIO3_BASE + GPIO_IRQSTATUS_RAW_1_OFFSET)
#define GPIO3_IRQSTATUS_0 (GPIO3_BASE + GPIO_IRQSTATUS_0_OFFSET)
#define GPIO3_IRQSTATUS_1 (GPIO3_BASE + GPIO_IRQSTATUS_1_OFFSET)
#define GPIO3_IRQSTATUS_SET_0 (GPIO3_BASE + GPIO_IRQSTATUS_SET_0_OFFSET)
#define GPIO3_IRQSTATUS_SET_1 (GPIO3_BASE + GPIO_IRQSTATUS_SET_1_OFFSET)
#define GPIO3_IRQSTATUS_CLR_0 (GPIO3_BASE + GPIO_IRQSTATUS_CLR_0_OFFSET)
#define GPIO3_IRQSTATUS_CLR_1 (GPIO3_BASE + GPIO_IRQSTATUS_CLR_1_OFFSET)
#define GPIO3_IRQWAKEN_0 (GPIO3_BASE + GPIO_IRQWAKEN_0_OFFSET)
#define GPIO3_IRQWAKEN_1 (GPIO3_BASE + GPIO_IRQWAKEN_1_OFFSET)
#define GPIO3_SYSSTATUS (GPIO3_BASE + GPIO_SYSSTATUS_OFFSET)
#define GPIO3_CTRL (GPIO3_BASE + GPIO_CTRL_OFFSET)
#define GPIO3_OE (GPIO3_BASE + GPIO_OE_OFFSET)
#define GPIO3_DATAIN (GPIO3_BASE + GPIO_DATAIN_OFFSET)
#define GPIO3_DATAOUT (GPIO3_BASE + GPIO_DATAOUT_OFFSET)
#define GPIO3_LEVELDETECT0 (GPIO3_BASE + GPIO_LEVELDETECT0_OFFSET)
#define GPIO3_LEVELDETECT1 (GPIO3_BASE + GPIO_LEVELDETECT1_OFFSET)
#define GPIO3_RISINGDETECT (GPIO3_BASE + GPIO_RISINGDETECT_OFFSET)
#define GPIO3_FALLINGDETECT (GPIO3_BASE + GPIO_FALLINGDETECT_OFFSET)
#define GPIO3_DEBOUNCENABLE (GPIO3_BASE + GPIO_DEBOUNCENABLE_OFFSET)
#define GPIO3_DEBOUNCINGTIME (GPIO3_BASE + GPIO_DEBOUNCINGTIME_OFFSET)
#define GPIO3_CLEARDATAOUT (GPIO3_BASE + GPIO_CLEARDATAOUT_OFFSET)
#define GPIO3_SETDATAOUT (GPIO3_BASE + GPIO_SETDATAOUT_OFFSET)

#endif /* _GPIO_H */